name: SnakeBlock
version: @version@
main: net.kunmc.lab.snakeblock.Main
api-version: 1.15
depend: [NoteBlockAPI]
commands:
  snake:
    usage: "/snake help"
    description: "snakeBlockPlugin by Propromp"

permissions:
  snake.help:
    default: op
  snake.start:
    default: op
  snake.stop:
    default: op
  snake.startgame:
    default: op
  snake.stopgame:
    default: op
  snake.setup:
    default: op
  snake.delete:
    default: op
  snake.bgm:
    default: op
  snake.adhd:
    default: op
  snake.selector:
    default: op
  snake.*:
    children:
      - snake.help
      - snake.start
      - snake.stop
      - snake.startgame
      - snake.stopgame
      - snake.setup
      - snake.delete
      - snake.bgm
      - snake.adhd
      - snake.selector